### ISSUE TITLE
Pin-Nummerierung

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#10]
Es scheint aktuell so, dass man die Header-Pin-Nummerierung angeben muss, nicht die wiring-Pi-Nummer. Macht das bei unterschiedlichen PI Versionen Ärger? Wie geht die Lib damit um?

**Comment by moho1** [comment]
Ich habe gerade nochmal die nachgeschaut, ich war auch etwas verwirrt: `GPIO.setmode(GPIO.BOARD)` setzt das Pin Numbering auf die Pins, wie sie auf dem Board angeordnet sind. Das hat dann nichts mehr mit den GPIO Nummern zu tun.

Dies ist auch die Variante, die Portabler zwischen verschiedenen Pi-Versionen ist, da sich die Anordnung der GPIO Nummern zwischen den Versionen geändert hat. So sind die LEDs mit dem C9000 Board jetzt immer auf Pin 24/26. Die GPIOs dort wären je nach Pi-Modell 10/11 oder 7/8.

Falls ungültige Pinnummern, auf denen es keinen GPIO gibt, angegeben werden, fängt die Library das ab.
