### ISSUE TITLE
Presets einbauen

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#11]
Z.B. für C9000 einen Parameter --c9000, der dann die Pin-Zuordnung automatisch setzt
``--gpioRun 24 --gpioConn 26``

**Comment by moho1** [comment]
Ich habe das in commit 63a9e4800e4b78c5aa3fb60dcd4533ef2fca951b, aber ein wenig anders, implementiert.

Es gibt jetzt den Parameter --preset, der ein Argument erwartet. Aktuell gibt es nur das Preset für den c9000, also --preset c9000.

--preset help gibt eine Liste an allen verfügbaren Presets inkl. Portmapping dieser aus.

**Comment by 7h0ma5** [comment]
Theoretisch könnte man auch die Config vom UniPager mit "GetConfig" abrufen und dann den Preset anhand des Sender-Typs automatisch wählen.

**Comment by moho1** [comment]
Das wäre ganz interessant, würde ich aber dann mit einem expliziten "auto" preset, welches dann auch bei keinen angegebenen LEDs standard ist, machen.

Das wäre bei der aktuellen Codestruktur aber entweder nur schwer oder nur unschön machbar, da die Websocketverbindung erst geöffnet wird nachdem die LEDs übergeben wurden.

Ich überlege mal, wie ich das machen kann...

**Comment by moho1** [comment]
Ich habe in 115dcfa73c988af4f6e1067ba05d4697dbd0d682 gerade mal eingebaut, dass, wenn keine LEDs angegeben wurden, versucht wird, die Config des UniPagers zu verwenden. Das funktioniert aktuell für den C9000.

Das heißt halt auch, dass auch wenn keine GPIOs angegeben werden beim starten ggf. ungewollt GPIOs getriggert werden.
