### ISSUE TITLE
Bessere Timeout Behandlung

### ISSUE THREAD

**Issue by moho1** [rwth-afu/UniPagerLED#12]
Aktuell wird sich mit dem 60 Sekunden Timeout darauf verlassen, dass spätestens alle 60 Sekunden eine Nachricht über den Websocket kommt. Dies sollte besser gelöst werden, indem nach einem Timeout der Server nochmal nach Daten gefragt wird und erst nach einem weiteren Timeout in Folge von einem Verbindungsabbruch ausgegangen wird.

**Comment by moho1** [comment]
UniPager sendet jetzt ja für jeden Timeslot eine neue Statusmessage. Sind die verlässlich? Falls ja könnte man auf diese Vertrauen und ein Ausbleiben dieser für >10 Sekunden als Connection Loss händeln.

Damit hätte sich diese Issue dann erledigt.
@7h0ma5

**Comment by 7h0ma5** [comment]
Ja, diese Nachrichten müssen alle 6 Sekunden kommen, sonst kann man davon ausgehen, dass ein schwerwiegendes Problem vorliegt.

**Comment by moho1** [comment]
ok, ich habe den timeout jetzt in 9be65701338dab04269e4d157082f1be3092de1f mal auf 10 sekunden gesenkt und mache kein weiteres handling von diesem.
