### ISSUE TITLE
Service-Datei für Systemd

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#14]
Könnte man mal erstellen, dann startet das Ding auch beim booten.

**Comment by 7h0ma5** [comment]
Habe ich im debian-Branch für das Debian-Paket schon erstellt. Damit man die Parameter in der Service-Datei nicht ändern muss, wäre eine Config-Datei praktisch.

**Comment by moho1** [comment]
Die Option für eine Konfigurationsdatei existiert jetzt und auch das servicefile sollte zusammen mit dem install.sh nutzbar sein.
