### ISSUE TITLE
Debug-Ausgaben optional

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#15]
Jens DL8SDL fragt:
````
[...]die Bildschirmausgabe unterbinden - im Idealfall sollte die Anwendung
ja wie der UniPager als beim Systemstart automatisch startender Dienst
laufen. Wie bewerkstellige ich das ?
[...]

**Comment by moho1** [comment]
Ich habe die Debugausgaben jetzt standardmäßig deaktiviert, aktiviert werden können sie mit --debug.

Meldungen bei Verlust der Verbindung zwischen UniPagerLED und dem UniPager werden aber weiterhin angezeigt.

Auch existiert jetzt eine Option für eine Konfigurationsdatei sowie ein systemd Service file und ein Install Skript.
