### ISSUE TITLE
make klappt nicht

### ISSUE THREAD

**Issue by MurrayBozinsky** [rwth-afu/UniPagerLED#2]
Hardware: RasPi3B
Software: RustPager0.42 vorkompiliert, läuft. RustPagerLED von gerade eben

pi@DM0AI-7:~/RustPagerLED $ sudo make
g++ -c -Wall -std=c++11 -pthread -Isrc/. -Isrc/websocket -c src/./main.cpp -o build/./main.o
g++ build/./main.o -o build/rustpagerled -lwiringPi -pthread -rdynamic -lboost_system -Wl,-Bstatic -lboost_coroutine -Wl,-Bdynamic -lboost_context -lboost_thread -lpthread -lcrypto -lpthread -ljson_spirit
/usr/bin/ld: cannot find -ljson_spirit
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'build/rustpagerled' failed
make: *** [build/rustpagerled] Error 1

**Comment by dk4pa** [comment]
Install "libjson-spirit-dev"

sudo apt install libjson-spirit-dev

**Comment by dh3wr** [comment]
Es ist noch nicht fertig. Keine LED Funktion. Wird auch auf Python umgestellt.

**Comment by moho1** [comment]
Ist jetzt in Python geschrieben. Logik ist schon vorhanden, nur das schalten der LEDs fehlt noch, das kommt in kürze.
