### ISSUE TITLE
LED Ansteuerung fehlt noch?

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#4]
Wiring pi taucht noch nicht auf, oder?

**Comment by moho1** [comment]
Nein, Wiring pi ist noch nicht drin. Ich wollte mir erstmal einen Pi aufsetzen, auf dem ich das dann mache. Sollen aber nur wenige Zeilen sein,  ggf. mache ich das heute abend noch schnell.

**Comment by moho1** [comment]
Ist jetzt drin.
