### ISSUE TITLE
Programm startet nicht, wenn nicht alle LED angegeben sind

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#5]
Wenn man nicht alle 3 GPIO Port definiert, startet das Programm nicht. Es wäre schön, wenn die Parameter optional sind, wobei bei keinem GPIO das Programm auch keinen Sinn macht und dann eine Fehlermeldung ausgeben sollte. Nicht alle Sender (insb. die C9000) haben eine extra TX-LED, da diese bereits im Geräte implementiert ist.

**Comment by moho1** [comment]
War ein Bug, da`hatte ich beim Einfügen der LEDs nicht aufgepasst. Ist jetzt gefixt
