### ISSUE TITLE
Wird die "Verbindung LED" geupdatet

### ISSUE THREAD

**Issue by dh3wr** [rwth-afu/UniPagerLED#7]
Was passiert z.B. hier 
````
self.ws = websocket.create_connection(url)
self.setled(self.bled, True)
````
Wenn die websocket-Verbindung nicht klappt?

**Comment by moho1** [comment]
Wenn die websocket-Verbindung nicht klappt wird eine Exeption geworfen, durch welche sich das Programm beendet. Die LED wird erst gesetzt, sobald die Websocket Verbindung aufgebaut ist.

Eine besser Fehlerbehandlung hier mit Wiederholung, wenn die Verbindung fehlschlägt bzw. abbricht, wäre gut.

Ich habe gerade auch noch andere Sachen zu tun, ggf. komme ich heute Abend dazu.

**Comment by moho1** [comment]
Mit commit 4efda14bbba286a2acd6245eeacb5444d7a3e44b sollte es jetzt eine bessere Fehlerbehandlung mit Wiederholungen und Fehler-Behandlung geben.
